# noinspection SqlNoDataSourceInspectionForFile
# --- !Ups

CREATE TABLE organisation (
    id BIGINT(20) NOT NULL AUTO_INCREMENT,
    name VARCHAR(255),
    description TEXT,
    email VARCHAR(255),
    website VARCHAR(255),
    location VARCHAR(255),
    category VARCHAR(255),
    subcategory VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE project (
    id BIGINT(20) NOT NULL AUTO_INCREMENT,
    name VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE account (
    id BIGINT(20) NOT NULL AUTO_INCREMENT,
    email VARCHAR(255),
    name VARCHAR(255),
    password VARCHAR(400), -- approximately the length of the hash generated by argon2 (with a bit more space)
    role BIGINT(20),
    PRIMARY KEY (id)
);

# --- !Downs

DROP TABLE account;
DROP TABLE organisation;
DROP TABLE project;
