# --- !Ups

-- Created and updated timestamps
ALTER TABLE account ADD COLUMN createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE account ADD COLUMN updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE comment ADD COLUMN createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE comment ADD COLUMN updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE comment_project ADD COLUMN createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE comment_project ADD COLUMN updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE comment_project_history ADD COLUMN createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE comment_project_history ADD COLUMN updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE organisation ADD COLUMN createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE organisation ADD COLUMN updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE project ADD COLUMN createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE project ADD COLUMN updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE project_history ADD COLUMN createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE project_history ADD COLUMN updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE rating ADD COLUMN createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE rating ADD COLUMN updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- Verification for organisations
ALTER TABLE organisation ADD COLUMN verified BOOLEAN DEFAULT FALSE;
ALTER TABLE organisation ADD COLUMN verifiedAt TIMESTAMP;

# --- !Downs

ALTER TABLE organisation DROP COLUMN createdAt;
ALTER TABLE organisation DROP COLUMN updatedAt;
ALTER TABLE organisation DROP COLUMN verified;
ALTER TABLE organisation DROP COLUMN verifiedAt;

ALTER TABLE account DROP COLUMN createdAt;
ALTER TABLE account DROP COLUMN updatedAt;

ALTER TABLE comment DROP COLUMN createdAt;
ALTER TABLE comment DROP COLUMN updatedAt;

ALTER TABLE comment_project DROP COLUMN createdAt;
ALTER TABLE comment_project DROP COLUMN updatedAt;

ALTER TABLE comment_project_history DROP COLUMN createdAt;
ALTER TABLE comment_project_history DROP COLUMN updatedAt;

ALTER TABLE project DROP COLUMN createdAt;
ALTER TABLE project DROP COLUMN updatedAt;

ALTER TABLE project_history DROP COLUMN createdAt;
ALTER TABLE project_history DROP COLUMN updatedAt;

ALTER TABLE rating DROP COLUMN createdAt;
ALTER TABLE rating DROP COLUMN updatedAt;
