'use strict'
respondecoApp.controller 'OrganizationsController', ($scope, $location, Organization) ->
  PAGESIZE = 20
  $scope.totalItems = null
  $scope.organizations = []
  $scope.currentPage = 1
  $scope.filter =
    pageSize: PAGESIZE
    fields: "name,logo"

  $scope.getOrganizations = ->
    $scope.filter.page = $scope.currentPage - 1
    Organization.query $scope.filter, (page) ->
      $scope.totalItems = page.totalItems
      $scope.organizations = page.organizations
      return
    return

  $scope.onPageChange = ->
    $scope.getOrganizations()
    return

  $scope.redirectToOrganization = (name) ->
    $location.path 'organization/' + name
    return

  $scope.redirectToNew = ->
    $location.path 'organization/edit/new'
    return

  $scope.getOrganizations()
  return

# ---
# generated by js2coffee 2.0.3