angular.module('respondecoAppFilters', []).filter('logo', ->
  (input) ->
    input or 'http://lorempixel.com/200/200/city/'
).filter('round', ->
  (input) ->
    (Math.round(input * 10) / 10).toString().replace '.', ','
).filter('formatUser', ->
  (user) ->
    name = ''
    if user != null
      if user.lastName != undefined and user.firstName != undefined
        name = user.firstName + ' ' + user.lastName + ' (' + user.login + ')'
      else if user.name == undefined or user.firstName == undefined
        name = user.login
    name
).filter('linkify', ->
  (link) -> "<a href='#{link}'>#{link}</a>"
).filter('default', ->
  (input, __default__) ->
    if input is null or input is undefined then __default__ else input
)

# ---
# generated by js2coffee 2.0.4