'use strict'

### Services ###
respondecoApp.factory 'LanguageService', ($http, $translate, LANGUAGES) ->
  { getBy: (language) ->
    if language == undefined
      language = $translate.storage().get('NG_TRANSLATE_LANG_KEY')
    if language == undefined
      language = 'en'
    promise = $http.get('/i18n/' + language + '.json').then((response) ->
      LANGUAGES
    )
    promise
 }

respondecoApp.factory 'Register', ($resource) ->
  $resource 'app/rest/register', {}, {}

respondecoApp.factory 'Activate', ($resource) ->
  $resource 'app/rest/activate', {}, 'get':
    method: 'GET'
    params: {}
    isArray: false

respondecoApp.factory 'Account', ($resource) ->
  $resource 'app/rest/account', {},
    leaveOrganization:
      method: 'POST'
      url: 'app/rest/account/leaveorganization'
    getNewsfeed:
      method: 'GET'
      url: 'app/rest/account/newsfeed'
    setProfilePicture:
      method: 'POST'
      url: 'app/rest/account/profilepicture'

respondecoApp.factory 'Password', ($resource) ->
  $resource 'app/rest/account/change_password', {}, {}

respondecoApp.factory 'Sessions', ($resource) ->
  $resource 'app/rest/account/sessions/:series', {}, 'get':
    method: 'GET'
    isArray: true

respondecoApp.factory 'Session', ->
  # TODO remove everything except account
  @create = (account) ->
    @login = account.login
    @firstName = account.firstName
    @lastName = account.lastName
    @email = account.email
    @userRoles = account.roles
    @profilePicture = account.profilePicture

  @invalidate = ->
    @login = null
    @firstName = null
    @lastName = null
    @email = null
    @userRoles = null

  @valid = -> @login isnt null and @login isnt undefined

  @

respondecoApp.factory 'AuthenticationSharedService', ($rootScope, $http, authService, Session, Account, USER_ROLES) ->
  @login = (param) ->
    data = 'j_username=' + encodeURIComponent(param.username) + '&j_password=' + encodeURIComponent(param.password) + '&_spring_security_remember_me=' + param.rememberMe + '&submit=Login'
    $http.post('app/authentication', data,
      headers: 'Content-Type': 'application/x-www-form-urlencoded'
      ignoreAuthModule: 'ignoreAuthModule').success((data, status, headers, config) ->
      Account.get (data) ->
        if data.login != 'anonymousUser'
          Session.create data
          $rootScope.account = Session
          $rootScope._account = data
          authService.loginConfirmed data
    ).error (data, status, headers, config) ->
      $rootScope.authenticationError = true
      Session.invalidate()

  @refresh= ->
    Account.get (data) ->
      if data.login != 'anonymousUser'
        Session.create data
        $rootScope.account = Session
        $rootScope._account = data

  @valid = (authorizedRoles) ->
    $http.get('protected/authentication_check.gif', ignoreAuthModule: 'ignoreAuthModule').success((data, status, headers, config) ->
      if !Session.login
        Account.get (data) ->
          if data.login != 'anonymousUser'
            Session.create data
            $rootScope.account = Session
            $rootScope._account = data
            $rootScope.authenticated = true
            $rootScope.$broadcast 'event:authenticated', data
      $rootScope.authenticated = ! !Session.login
    ).error (data, status, headers, config) ->
      $rootScope.authenticated = false
      if !$rootScope.isAuthorized(authorizedRoles)
        $rootScope.$broadcast 'event:auth-loginRequired', data

  @isAuthorized = (authorizedRoles) ->
    if authorizedRoles == null
      authorizedRoles = [ USER_ROLES.user ]
    if !angular.isArray(authorizedRoles)
      if authorizedRoles == '*'
        authorizedRoles = [ authorizedRoles ]
    isAuthorized = false
    angular.forEach authorizedRoles, (authorizedRole) ->
      authorized = ! !Session.login and Session.userRoles.indexOf(authorizedRole) != -1
      if authorized or authorizedRole == '*'
        isAuthorized = true
    isAuthorized

  @logout = ->
    $rootScope.authenticationError = false
    $rootScope.authenticated = false
    $rootScope.account = null
    $rootScope._account = null
    $http.get 'app/logout'
    Session.invalidate()
    authService.loginCancelled()

  @
# ---
# generated by js2coffee 2.1.0