angular.module('respondecoAppFilters', []).filter('logo', ->
  (input) ->
    input or 'http://lorempixel.com/200/200/city/'
).filter('round', ->
  (input) ->
    (Math.round(input * 10) / 10).toString().replace '.', ','
).filter('formatUser', ->
  (user, length) ->
    length = length or 'long'
    name = ''
    if user isnt null and user isnt undefined
      if length is 'long'
        if user.lastName isnt undefined and user.firstName isnt undefined
          name = user.firstName + ' ' + user.lastName + ' (' + user.login + ')'
      else if length is 'login' then name = user.login
      else if length is 'short' then name = "#{user.firstName} #{user.lastName}"
      else if length is 'first' then name = user.firstName
      else if length is 'last' then name = user.lastName
    name
).filter('userImage', ->
  (user) ->
    if user?.profilePicture isnt null and user?.profilePicture isnt undefined then "/app/rest/images/file/#{user.profilePicture.id}"
    else '/images/profile_empty.png'
).filter('linkify', ->
  (link) -> "<a href='#{link}'>#{link}</a>"
).filter('default', ->
  (input, __default__) ->
    if input is null or input is undefined then __default__ else input
)

# ---
# generated by js2coffee 2.0.4